[workspace]
resolver = "3"
members = [
    "arche-web",
    "firestore-common",
    "phylax-core",
    "phylax-gcp",
    "phylax-oidc",
]

[workspace.package]
edition = "2024"
license = "AGPL-3.0-only"
repository = "https://github.com/khoek/rete"
publish = ["crates-io"]

[workspace.dependencies]
firestore-common = { path = "firestore-common", version = "0.1" }
phylax-core = { path = "phylax-core", version = "0.1" }

anyhow = "1"
base64 = "0.23"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = { version = "2", features = ["serde"] }
